# docker-compose.yml
version: '3.8'

services:
  webapp:
    container_name: portfolio

    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - /DATA/AppData/portfolio/app
      - /DATA/AppData/portfolio/app/node_modules
    restart: unless-stopped