/*
  Auto-generated by Spline
*/
"use client"
import useSpline from '@splinetool/r3f-spline'
import { OrthographicCamera } from '@react-three/drei'
import { Canvas } from '@react-three/fiber'

export default function Scene({ ...props }) {
  const { nodes, materials } = useSpline('https://prod.spline.design/HMdyIm8draRO3-2A/scene.splinecode')
  return (
    <div>
    <Canvas className='z-50 flex absolute justify-center'>
      <color attach="background" args={['#000000']} />
      <group {...props} dispose={null}>
        <scene name="Scene">
          <OrthographicCamera
            name="Camera"
            makeDefault={true}
            far={100000}
            near={-100000}
            up={[0, 1, 0]}
            position={[-0.05, 268.47, 861.64]}
            rotation={[-0.3, 0, 0]}
            scale={1}
          />
          <mesh
            name="Text"
            geometry={nodes.Text.geometry}
            material={materials['']}
            castShadow
            receiveShadow
            position={[7.62, -36.45, -46.97]}
            rotation={[-0.09, 0, 0]}
            scale={[2.4, 2.4, 7.06]}
          />
          <group name="Group">
            <group name="Group 3" scale={0.58}>
              <group name="Group 2" position={[0, 0, 0]} rotation={[0, 0, 0]} scale={1}>
                <group name="rocket" position={[0, 0, 150]} scale={0.5}>
                  <mesh
                    name="Cube 4"
                    geometry={nodes['Cube 4'].geometry}
                    material={materials['Untitled Material']}
                    castShadow
                    receiveShadow
                    position={[24.15, -26.02, 0.36]}
                    rotation={[0, -Math.PI / 2, 0]}
                    scale={[0.05, 0.33, 1]}
                  />
                  <mesh
                    name="Cube 3"
                    geometry={nodes['Cube 3'].geometry}
                    material={materials['Untitled Material']}
                    castShadow
                    receiveShadow
                    position={[-24.15, -26.02, 0.36]}
                    rotation={[0, Math.PI / 2, 0]}
                    scale={[0.05, 0.33, 1]}
                  />
                  <mesh
                    name="Cube 2"
                    geometry={nodes['Cube 2'].geometry}
                    material={materials['Untitled Material']}
                    castShadow
                    receiveShadow
                    position={[1.4, -23.04, 27.17]}
                    rotation={[-2.99, 0, Math.PI]}
                    scale={[0.05, 0.33, 1]}
                  />
                  <mesh
                    name="Cube"
                    geometry={nodes.Cube.geometry}
                    material={materials['Untitled Material']}
                    castShadow
                    receiveShadow
                    position={[1.4, -24.8, -27.4]}
                    rotation={[-0.13, 0, 0]}
                    scale={[0.05, 0.33, 1]}
                  />
                  <mesh
                    name="Cylinder"
                    geometry={nodes.Cylinder.geometry}
                    material={materials['Cylinder Material']}
                    castShadow
                    receiveShadow
                    position={[-0.14, -10.38, -0.54]}
                    scale={[0.39, 0.61, 0.39]}
                  />
                </group>
              </group>
            </group>
            <mesh
              name="Cylinder1"
              geometry={nodes.Cylinder1.geometry}
              material={materials['Cylinder1 Material']}
              castShadow
              receiveShadow
              rotation={[0, 0, 2.94]}
              scale={[4.67, 0.05, 4.67]}
            />
            <mesh
              name="Sphere"
              geometry={nodes.Sphere.geometry}
              material={materials['Sphere Material']}
              castShadow
              receiveShadow
              scale={0.7}
            />
          </group>
          <directionalLight
            name="Directional Light"
            castShadow
            intensity={1.2}
            shadow-mapSize-width={1024}
            shadow-mapSize-height={1024}
            shadow-camera-near={-10000}
            shadow-camera-far={100000}
            shadow-camera-left={-50}
            shadow-camera-right={50}
            shadow-camera-top={50}
            shadow-camera-bottom={-50}
            color="#fef9df"
            position={[-775.61, 741.54, 1126.74]}
          />
          <OrthographicCamera name="1" makeDefault={false} far={10000} near={-50000} />
          <hemisphereLight name="Default Ambient Light" intensity={0.75} color="#eaeaea" />
        </scene>
      </group>
    </Canvas>
    </div>
  )
}
